# Generated by Django 5.1.7 on 2025-03-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comment',
        ),
    ]
