# Generated by Django 5.1.7 on 2025-03-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_post_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
